<# 
.SYNOPSIS
Creates a HomeOps weapon preview manifest from a trusted sample folder.

.EXAMPLE
powershell -ExecutionPolicy Bypass -File scripts/redux-preview/create_weapon_preview_manifest.ps1 -Folder C:\Samples\weapon

.NOTES
This helper only lists files and writes JSON. It does not execute, parse, convert, extract, or modify source files.
#>

param(
	[Parameter(Mandatory = $true)]
	[string]$Folder,

	[string]$OutputPath = "",

	[switch]$Recurse
)

$ErrorActionPreference = "Stop"

$resolvedFolder = Resolve-Path -LiteralPath $Folder
if (-not $OutputPath) {
	$OutputPath = Join-Path $resolvedFolder "weapon_preview_manifest.json"
}

$extensions = @(".ydr", ".yft", ".ydd", ".ytd", ".meta", ".ymt", ".glb", ".gltf")
$files = Get-ChildItem -LiteralPath $resolvedFolder -File -Recurse:$Recurse |
	Where-Object { $extensions -contains $_.Extension.ToLowerInvariant() } |
	Sort-Object Name

function Get-Role($file) {
	$ext = $file.Extension.ToLowerInvariant()
	$name = $file.BaseName.ToLowerInvariant()

	if ($ext -eq ".ytd") { return "texture_dictionary" }
	if ($ext -eq ".yft") { return "fragment" }
	if ($ext -eq ".ydd") { return "drawable_dictionary" }
	if ($ext -eq ".meta" -or $ext -eq ".ymt") { return "metadata" }
	if ($name -like "*_hi") { return "high_model" }
	return "model"
}

$previewFile = $files | Where-Object { $_.Extension.ToLowerInvariant() -in @(".glb", ".gltf") } | Select-Object -First 1
$sourceFiles = @(
	foreach ($file in $files) {
		$ext = $file.Extension.ToLowerInvariant()
		if ($ext -in @(".glb", ".gltf")) { continue }
		[ordered]@{
			fileName = $file.Name
			extension = $ext
			role = Get-Role $file
			status = if ($ext -in @(".ydr", ".yft", ".ydd", ".ytd")) { "unsupported" } else { "present" }
		}
	}
)

$manifest = [ordered]@{
	manifestVersion = "1.0.0"
	previewId = (Split-Path -Leaf $resolvedFolder)
	displayName = "Weapon Preview"
	weaponName = "Detected Weapon Sample"
	sourceLabel = $resolvedFolder.Path
	sourceKind = if ($previewFile) { "manual_glb" } else { "unsupported_gta_resource" }
	previewStatus = if ($previewFile) { "ready" } else { "converter_not_connected" }
	previewModel = if ($previewFile) {
		[ordered]@{
			url = $previewFile.Name
			format = $previewFile.Extension.TrimStart(".").ToLowerInvariant()
			sizeBytes = $previewFile.Length
			hash = $null
		}
	} else {
		$null
	}
	sourceFiles = $sourceFiles
	textureSlots = @(
		[ordered]@{ slotName = "diffuse"; textureName = ""; status = "converter not connected"; notes = "Populate after GLB conversion." },
		[ordered]@{ slotName = "normal"; textureName = ""; status = "converter not connected"; notes = "Browser does not parse .ytd directly." },
		[ordered]@{ slotName = "specular"; textureName = ""; status = "converter not connected"; notes = "Populate after GLB conversion." },
		[ordered]@{ slotName = "tint"; textureName = ""; status = "waiting for converter"; notes = "Optional future metadata." }
	)
	warnings = @(
		if (-not $previewFile) { "Converter not connected - showing demo placeholder." },
		"GTA .ydr/.yft/.ydd/.ytd files are detected only; this helper never parses or converts them."
	)
	notes = @(
		"Generated by scripts/redux-preview/create_weapon_preview_manifest.ps1.",
		"Run with -Recurse only for small trusted sample folders."
	)
}

$manifest | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $OutputPath -Encoding UTF8
Write-Output "Wrote $OutputPath"
