<# 
.SYNOPSIS
Creates a HomeOps weapon preview manifest from a trusted sample folder.

.EXAMPLE
powershell -ExecutionPolicy Bypass -File scripts/redux-preview/create_weapon_preview_manifest.ps1 -Folder C:\Samples\weapon

.NOTES
This helper only lists files and writes JSON. It does not execute, parse, convert, extract, or modify source files.
#>

param(
	[Parameter(Mandatory = $true)]
	[string]$Folder,

	[string]$OutputPath = "",

	[switch]$Recurse
)

$ErrorActionPreference = "Stop"

$resolvedFolder = Resolve-Path -LiteralPath $Folder
if (-not $OutputPath) {
	$OutputPath = Join-Path $resolvedFolder "weapon_preview_manifest.json"
}

$extensions = @(".ydr", ".yft", ".ydd", ".ytd", ".meta", ".ymt", ".glb", ".gltf")
$files = Get-ChildItem -LiteralPath $resolvedFolder -File -Recurse:$Recurse |
	Where-Object { $extensions -contains $_.Extension.ToLowerInvariant() } |
	Sort-Object Name

function Get-Role($file) {
	$ext = $file.Extension.ToLowerInvariant()
	$name = $file.BaseName.ToLowerInvariant()

	if ($ext -eq ".ytd") { return "texture_dictionary" }
	if ($ext -eq ".yft") { return "fragment_model" }
	if ($ext -eq ".ydd") { return "drawable_dictionary" }
	if ($ext -eq ".meta" -or $ext -eq ".ymt") { return "metadata" }
	if ($name -like "*_hi") { return "high_drawable_model" }
	if ($ext -eq ".ydr") { return "drawable_model" }
	return "unknown"
}

$previewFile = $files | Where-Object { $_.Extension.ToLowerInvariant() -in @(".glb", ".gltf") } | Select-Object -First 1
$sourceFiles = @(
	foreach ($file in $files) {
		$ext = $file.Extension.ToLowerInvariant()
		if ($ext -in @(".glb", ".gltf")) { continue }
		[ordered]@{
			fileName = $file.Name
			relativePath = $file.Name
			extension = $ext
			role = Get-Role $file
			sizeBytes = $file.Length
			sha256 = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
			status = "present"
		}
	}
)

$textureDictionaries = @(
	foreach ($file in $sourceFiles | Where-Object { $_.role -eq "texture_dictionary" }) {
		[ordered]@{
			fileName = $file.fileName
			textureNames = @()
			status = "texture mapping not available yet"
		}
	}
)

$manifest = [ordered]@{
	manifestVersion = "1.0.0"
	previewId = (Split-Path -Leaf $resolvedFolder)
	displayName = "Weapon Preview"
	weaponName = "Detected Weapon Sample"
	weaponPrefix = $null
	sourceLabel = $resolvedFolder.Path
	sourceKind = if ($previewFile) { "manual_glb" } else { "unsupported_gta_resource" }
	previewStatus = if ($previewFile) { "ready" } else { "converter_not_configured" }
	modelPreview = if ($previewFile) {
		[ordered]@{
			url = $previewFile.Name
			format = $previewFile.Extension.TrimStart(".").ToLowerInvariant()
			sizeBytes = $previewFile.Length
			sha256 = (Get-FileHash -LiteralPath $previewFile.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
			generatedAt = $null
		}
	} else {
		$null
	}
	sourceFiles = $sourceFiles
	textureDictionaries = $textureDictionaries
	materialSlots = @(
		[ordered]@{ slotName = "diffuse"; textureName = ""; sourceYtd = $null; status = "converter not configured"; notes = "Populate after GLB conversion." },
		[ordered]@{ slotName = "normal"; textureName = ""; sourceYtd = $null; status = "converter not configured"; notes = "Browser does not parse .ytd directly." },
		[ordered]@{ slotName = "specular"; textureName = ""; sourceYtd = $null; status = "converter not configured"; notes = "Populate after GLB conversion." },
		[ordered]@{ slotName = "tint"; textureName = ""; sourceYtd = $null; status = "waiting for converter"; notes = "Optional future metadata." }
	)
	conversion = [ordered]@{
		gtaToGlbStatus = if ($previewFile) { "ready" } else { "not_configured" }
		glbToGtaStatus = "unsupported"
		converterName = if ($previewFile) { "manual local GLB" } else { $null }
		converterVersion = $null
		logsPath = $null
		warnings = @(
			if (-not $previewFile) { "No trusted converter produced preview GLB/GLTF." }
		)
	}
	reverseTemplate = [ordered]@{
		templateWeaponName = $null
		originalSourceFiles = @($sourceFiles | ForEach-Object { $_.relativePath })
		requiredFiles = @()
		stagedOutputDir = $null
		validationStatus = "unsupported"
	}
	warnings = @(
		if (-not $previewFile) { "Converter not configured - showing demo placeholder." },
		"GTA .ydr/.yft/.ydd/.ytd files are detected only; this helper never parses or converts them."
	)
	notes = @(
		"Generated by scripts/redux-preview/create_weapon_preview_manifest.ps1.",
		"Run with -Recurse only for small trusted sample folders."
	)
	buildReady = $false
}

$manifest | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $OutputPath -Encoding UTF8
Write-Output "Wrote $OutputPath"
